export default {
    message: {
        bold: '粗体',
        italic: '斜体',
        strike: '删除线',
        underline: '下划线',
        code: '代码',
        code_block: '代码块',
        paragraph: '段落',
        h1: '标题1',
        h2: '标题2',
        h3: '标题3',
        bullet_list: '无序列表',
        ordered_list: '有序列表',
        horizontal_rule: '插入分割线',
        link: '插入链接',
        blockquote: '块引用',
        redo: '重做',
        undo: '撤销',
        image: '插入图片',
    },
};
